[package]
name = "prisma"
version = "0.0.0"
authors = ["Dominic Petrick <petrick@prisma.io>", "Julius de Bruijn <bruijn@prisma.io>", "Marcus Böhm <boehm@prisma.io>" ]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
prost = "0.4"
prost-derive = "0.4"
prost-types = "0.4"
bytes = "0.4"
lazy_static = "1.2"
r2d2 = "0.8"
r2d2-sqlite3 = { path = "../libs/r2d2-sqlite3" }
sqlite = "0.24"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
serde_yaml = "0.8"
uuid = "0.7"
arc-swap = "0.3"
log = "0.4"
env_logger = "0.6"
tower-service = "0.2"
futures = "0.1"
tokio = "0.1"
prisma-query = { git = "https://github.com/prisma/prisma-query.git", branch = "sqlite_backend" }
prisma-common = { path = "../libs/prisma-common" }
prisma-models = { path = "../prisma-models" }

[build-dependencies]
prost-build = "0.4"
